title: Luciano Righetti
email: luciano [dot] righetti [at] gmail.com
description: Some of the hobby projects I've made so far.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://lucciano.github.io
twitter_username: xluccianox
github_username:  xluccianox

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Custom settings
show_excerpts: true
excerpt_separator: <!--more-->

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
